version: '3.8'
services:
  irma-ui:
    container_name: irma-ui
    build:
      context: .
      dockerfile: Dockerfile
    image: ${DOCKER_USERNAME:-integreative}/irma-ui:${VERSION:-1.0.0}
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - NODE_ENV=production
    networks:
      - irma-network

  irma-nginx:
    container_name: irma-nginx
    build:
      context: .
      dockerfile: Dockerfile.nginx
    image: ${DOCKER_USERNAME:-integreative}/irma-nginx:${VERSION:-1.0.0}
    ports:
      - "80:80"
    depends_on:
      - irma-ui
    networks:
      - irma-network

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongodb_data:/data/db

networks:
  irma-network:
    driver: bridge

volumes:
  mongodb_data: